default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: book_summarizer_2_development

test:
  <<: *default
  database: book_summarizer_2_test

production:
  <<: *default
  database: book_summarizer_2_production
  url: <%= ENV['DATABASE_URL'] %>
